routes/admin.php
<?php

use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\BrandsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ClientsController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\LocaleController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\BannerController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
    Route::get('home', [MainController::class, 'index'])->name('home');

    Route::resource('news', NewsController::class);
    Route::resource('language', LocaleController::class);
    Route::resource('clients', ClientsController::class);
    Route::resource('config', ConfigController::class);
    Route::resource('currency', CurrencyController::class);
    Route::get('convert_currency', [CurrencyController::class, 'ServiceConvertCurrency'])->name('convert_currency');
    Route::resource('categories', CategoryController::class);
    Route::resource('brands', BrandsController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('products', ProductController::class);
    Route::resource('order', OrderController::class);
    Route::resource('promotions', PromotionController::class);
    Route::resource('banners', BannerController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['LanguageMiddleware'])->group(function () {

    Route::get('/', [HomeController::class, 'index']);

    Route::get('/lang/{locale}', function ($locale) {
        if (!in_array($locale, ['en', 'ru'])) {
            abort(404);
        }
        session()->put('locale', $locale);
        return back();
    });

    Route::resource('products', ProductController::class);
    Route::get('products/filter/{filter}', [ProductController::class, 'filter']);
    Route::post('products/search', [ProductController::class, 'search']);

    Route::resource('about', AboutController::class);

    Route::resource('news', NewsController::class);

    Route::resource('promotions', PromotionController::class);

    Route::resource('orders', OrderController::class);

    /*Auth::routes([
        'login'    => false, // I ve mafe authorization via API - Evgeniy Tsoy
        'logout'   => true, // I will delete token on frontend - Evgeniy Tsoy
        'register' => true,
        'reset'    => true,   // for resetting passwords
        'confirm'  => false,  // for additional password confirmations
        'verify'   => false,  // for email verification
    ]);*/


// Authentication Routes...
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login']);
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

//Route::get('/admin/home', [\App\Http\Controllers\HomeController::class, 'index']);



    Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
        Lfm::routes();
    });


});

resources/views/admin/config.blade.php
@extends('layouts.admin')

@section('content')
    @php
        $langs = \App\Helpers\SysConfig::AllLanguage();
    @endphp
    <div class="col-md-12">
        <div class="card card-cascade cascading-admin-card user-card">
            @include('admin.blocks.card_head', ["title" => "Конфигурация", "title_child" => "Настройки", "icon" => "fa-cog"])
            <form method="post" action="{{ route('admin.config.store') }}"  enctype="multipart/form-data">
                @csrf
                <div class="card-body card-body-cascade">
                    <div class="row">
                        <div class="col-md-6">
                            <h2>Основные параметры</h2>
                            <hr />
                            <div class="form-group row">
                                <label class="col-md-3">Логотип</label>
                                <div class="col-md-7">
                                    <input class="form-control needs-validation" type="file" id="formFile" name="logo">
                                </div>
                                <div class="col-md-2">
                                    <div class="mb-12">
                                        @isset($data->logo)
                                        <img src="{{ asset($data->logo)}}" class="img-fluid" style="max-height: 50px;">
                                        <input type="hidden" name="logo_bk" value="{{ $data->logo }}">
                                        @endempty
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-3">Иконка</label>
                                <div class="col-md-7">
                                    <input class="form-control needs-validation" type="file" id="formFile" name="icon">
                                </div>
                                <div class="col-md-2">
                                    <div class="mb-12">
                                        @isset($data->icon)
                                            <img src="{{ asset($data->icon)}}" class="img-fluid" style="max-height: 50px;">
                                            <input type="hidden" name="icon_bk" value="{{ $data->icon }}">
                                        @endempty
                                    </div>
                                </div>
                            </div>

                            @foreach($langs as $lang)
                                @if(count($addr[$lang->code] ?? $addr) > 0)

                                        <div class="form-group row">
                                            <label class="col-md-3">Адрес ({{ $lang->code }})</label>
                                            <div class="col-md-9" id="address_{{ $lang->code }}">
                                                @foreach($addr[$lang->code] as $i)
                                                    @php
                                                        $ids = rand(0, 10000);
                                                    @endphp
                                                    @if ($loop->first)
                                                        <div class="input-group mb-3">
                                                            <input type="text" class="form-control" name="address[{{$lang->code}}][]" value="{{ $i->address }}">
                                                            <span class="input-group-text btn-primary address" data="{{ $lang->code }}"><i class="fas fa-plus"></i></span>
                                                        </div>
                                                    @else
                                                        <div class="input-group mb-3" id="{{ $ids }}">
                                                            <input type="text" class="form-control" name="address[{{$lang->code}}][]" value="{{ $i->address }}">
                                                            <span class="input-group-text btn-danger address" onclick="deleteAdress({{ $ids }})"><i class="fas fa-trash"></i></span>
                                                        </div>
                                                    @endif
                                                @endforeach
                                            </div>
                                        </div>
                                @endif
                            @endforeach

                            <div class="form-group row">
                                <label class="col-md-3">E-mail</label>
                                <div class="col-md-9">
                                    <input type="email" class="form-control" name="email" value="{{ $data->email ?? '' }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-md-3">Номер телефона</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control" name="phone" value="{{ $data->phone ?? '' }}">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <h2>Страница "О НАС"</h2>
                            <hr />
                            <div class="form-group row">
                                <label for="formFile" class="col-md-4">Картинка</label>
                                <div class="col-md-8">
                                    <div class="mb-3">
                                        <input class="form-control needs-validation" type="file" id="formFile" name="image_about">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="mb-12">
                                        @isset($about->image)
                                        <img src="{{ asset($about->image)}}" class="img-fluid" style="max-height: 400px;">
                                            <input type="hidden" name="about_img_bk" value="{{ $about->image }}">
                                        @endempty
                                    </div>
                                </div>
                            </div>

                            <div class="classic-tabs">
                                <div class="tabs-wrapper">
                                    <ul class="nav tabs-blue" role="tablist">
                                        @foreach($langs as $i=>$lang)
                                            <li class="nav-item">
                                                <a
                                                    class="nav-link waves-light waves-effect waves-light {{ ($i == 0) ? 'active' : '' }}"
                                                    data-toggle="tab"
                                                    href="#tab_{{ $lang->id }}"
                                                    role="tab"
                                                    aria-selected="true">
                                                    {{ $lang->name }} ({{ $lang->code }})
                                                </a>
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                                <div class="tab-content card">
                                    @foreach($langs as $i=>$lang)
                                        <div class="tab-pane fade {{ ($i == 0) ? 'active show' : '' }}" id="tab_{{ $lang->id }}" role="tabpanel">
                                            <div class="form-group">
                                                <label>Описание ({{ $lang->code }})</label>
                                                @include('admin.components.html_editor', ["name" => "about[translations][$lang->code][content_main]", "value" => $about ? $about->translate($lang->code)->content_main : ''])
                                            </div>
                                            <div class="form-group">
                                                <label>Описание ({{ $lang->code }})</label>
                                                @include('admin.components.html_editor', ["name" => "about[translations][$lang->code][content_page]", "value" => $about ? $about->translate($lang->code)->content_page : ''])
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-success"><i class="fas fa-save"></i> Сохранить</button>
                </div>
            </form>
        </div>

    </div>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.admin')

@section('content')
    <h2
        class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200 col-12"
    >
        Главная
    </h2>
    <div class="col-12 pt-3 row show_limited">
        @foreach($counts as $count)
            <div class="col-4 mb-3">
            <div class="card widget-flat">
                <div class="card-body d-flex justify-content-between">
                    <div>
                        <h5 class="text-muted fw-normal mt-0" title="{{ $count['title'] }}">{{ $count['title'] }}</h5>
                        <h3 class="mt-3 mb-3">{{ $count['data'] }}</h3>
                    </div>
                    <div class="d-flex flex-column align-items-end">
                        <div class="badge badge-primary p-2">
                            <i class="{{ $count['icon'] }} fa-2x"></i>
                        </div>
                        <a href="{{ asset($count['link']) }}" class="btn btn-outline-primary mr-0">Посмотреть</a>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
        <div class="col-12 d-flex justify-content-center">
            <button class="btn btn-primary" data-toggle="collapse" data-target="#collapseCard">Посмотреть больше</button>
        </div>
    </div>
    <div class="col-12 pt-3 row">
        <div class="col-6">
            <div class="card">
                <h4 class="m-0 pt-2 pl-2">Последние 5 выполненных заказов</h4>
                <hr class="my-2">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Продукт</th>
                        <th scope="col">Количество</th>
                        <th scope="col">Дата</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(count($recentServedOrders) > 0)
                    @foreach($recentServedOrders as $order)
                        <tr>
                            <th scope="row">{{ $order->product->name }}</th>
                            <td>{{ $order->product->sku }}</td>
                            <td>{{ $order->quantity }}</td>
                            <td>{{ $order->created_at }}</td>
                        </tr>
                    @endforeach
                    @else
                        <tr>
                            <td colspan="5" class="text-center">
                                Нет выполненных заказов
                            </td>
                        </tr>
                    @endif
                    </tbody>
                </table>
                <a href="{{ route('admin.order.index') }}" class="btn btn-outline-primary mr-0">Посмотреть</a>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <h4 class="m-0 pt-2 pl-2">Последние 5 не выполненных заказов</h4>
                <hr class="my-2">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Продукт</th>
                        <th scope="col">Количество</th>
                        <th scope="col">Дата</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(count($recentUnservedOrders) > 0)
                    @foreach($recentUnservedOrders as $order)
                    <tr>
                        <th scope="row">{{ $order->product->name }}</th>
                        <td>{{ $order->product->sku }}</td>
                        <td>{{ $order->quantity }}</td>
                        <td>{{ $order->created_at }}</td>
                    </tr>
                    @endforeach
                    @else
                        <tr>
                            <td colspan="5" class="text-center">
                                Нет не выполненных заказов
                            </td>
                        </tr>
                    @endif
                    </tbody>
                </table>
                <a href="{{ route('admin.order.index') }}" class="btn btn-outline-primary mr-0">Посмотреть</a>
            </div>
        </div>
    </div>
@endsection