routes/admin.php
<?php

use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\BrandsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ClientsController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\LocaleController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\BannerController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
    Route::get('home', [MainController::class, 'index'])->name('home');

    Route::resource('news', NewsController::class);
    Route::resource('language', LocaleController::class);
    Route::resource('clients', ClientsController::class);
    Route::resource('config', ConfigController::class);
    Route::resource('currency', CurrencyController::class);
    Route::get('convert_currency', [CurrencyController::class, 'ServiceConvertCurrency'])->name('convert_currency');
    Route::resource('categories', CategoryController::class);
    Route::resource('brands', BrandsController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('products', ProductController::class);
    Route::resource('order', OrderController::class);
    Route::resource('promotions', PromotionController::class);
    Route::resource('banners', BannerController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['LanguageMiddleware'])->group(function () {

    Route::get('/', [HomeController::class, 'index']);

    Route::get('/lang/{locale}', function ($locale) {
        if (!in_array($locale, ['en', 'ru'])) {
            abort(404);
        }
        session()->put('locale', $locale);
        return back();
    });

    Route::resource('products', ProductController::class);
    Route::get('products/filter/{filter}', [ProductController::class, 'filter']);
    Route::post('products/search', [ProductController::class, 'search']);

    Route::resource('about', AboutController::class);

    Route::resource('news', NewsController::class);

    Route::resource('promotions', PromotionController::class);

    Route::resource('orders', OrderController::class);

    /*Auth::routes([
        'login'    => false, // I ve mafe authorization via API - Evgeniy Tsoy
        'logout'   => true, // I will delete token on frontend - Evgeniy Tsoy
        'register' => true,
        'reset'    => true,   // for resetting passwords
        'confirm'  => false,  // for additional password confirmations
        'verify'   => false,  // for email verification
    ]);*/


// Authentication Routes...
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login']);
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

//Route::get('/admin/home', [\App\Http\Controllers\HomeController::class, 'index']);



    Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
        Lfm::routes();
    });


});

app/Models/Client.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer $id
 * @property string $name
 * @property ClientTranslation[] $clientsTranslations
 */
class Client extends Model implements TranslatableContract
{
    use Translatable;
    use SoftDeletes;
    public $translatedAttributes = ['content'];

    public $table = "clients";

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['name', 'image'];

    /**
     * @return HasMany
     */
    public function clientsTranslations()
    {
        return $this->hasMany('App\Models\ClientTranslation', 'clients_id');
    }
}

app/Http/Controllers/Admin/ClientsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Client;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Str;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $data = Client::translated()->paginate(env('PAGINATION_SIZE'));
        foreach ($data as $url) $url->image = asset($url->image);
        return view('admin.clients.main', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
//        Client::create($request->all());
        $client = new Client();
        $name = $request->get('name');
        $client->name = $name;
        $client->save();
        $logo = $request->file('logo');
        $extension = $logo->extension();
        $imageName = Str::random(40).'_';
        $path = 'clients/'.$client->id;

        $client->image = 'data/'.$path.'/'.$imageName.'.'.$extension;
        $logo->storeAs($path, str_replace('data/'.$path.'/', '', $client->image), 'uploads');
        $client->fill([
            'ru' => $request->get('ru'),
            'en' => $request->get('en')
        ]);
        $client->save();
        return Redirect::to(route('admin.clients.index'))->with('message', 'Сохранение прошло успешно');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit(int $id)
    {
        $data = Client::translated()->find($id);
        return view('admin.clients.edit', ['data' => $data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(Request $request, int $id)
    {
        $client = Client::find($id);
        $name = $request->get('name');
        $client->name = $name;
        $logo = $request->file('logo');
        if ($logo !== null) {
            file_exists($client->image) && unlink($client->image);
            $extension = $logo->extension();
            $imageName = Str::random(40).'_';
            $path = 'clients/'.$client->id;
            $client->image = 'data/'.$path.'/'.$imageName.'.'.$extension;
            $logo->storeAs($path, str_replace('data/'.$path.'/', '', $client->image), 'uploads');
        }
        $client->fill([
            'ru' => $request->get('ru'),
            'en' => $request->get('en')
        ]);
        $client->save();
        return Redirect::to(route('admin.clients.index'))->with('message', 'Сохранение прошло успешно');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy(int $id)
    {
        $client = Client::find($id);
        $folder_path = public_path('data/clients/'.$id);
        if (file_exists($folder_path)) {
            array_map('unlink', glob("$folder_path/*.*"));
            rmdir($folder_path);
        }
        $client->delete();
        return Redirect::to(route('admin.clients.index'))->with('message', 'Удаление прошло успешно');
    }
}

resources/views/admin/clients/create.blade.php
@extends('layouts.admin')

@section('content')
    @php
        $langs = \App\Helpers\SysConfig::AllLanguage();
    @endphp

    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card card-cascade cascading-admin-card user-card">
            @include('admin.blocks.card_head', ["title" => "Клиенты", "title_child" => "Создать", "icon" => "fa-users"])
            <form method="post" action="{{ route('admin.clients.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body card-body-cascade">
                    <div class="form-group row">
                        <label class="col-md-4">Наименование</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="name" value="" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-4">Логотип</label>
                        <div class="col-md-8">
                            <input type="file" name="logo">
                        </div>
                    </div>

                    <div class="classic-tabs">
                        <div class="tabs-wrapper">
                            <ul class="nav tabs-blue" role="tablist">
                                @foreach($langs as $i=>$lang)
                                    <li class="nav-item">
                                        <a
                                            class="nav-link waves-light waves-effect waves-light {{ ($i == 0) ? 'active' : '' }}"
                                            data-toggle="tab"
                                            href="#tab_{{ $lang->id }}"
                                            role="tab"
                                            aria-selected="true">
                                            {{ $lang->name }} ({{ $lang->code }})
                                        </a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>

                        <div class="tab-content card">
                            @foreach($langs as $i=>$lang)
                                <div class="tab-pane fade {{ ($i == 0) ? 'active show' : '' }}" id="tab_{{ $lang->id }}" role="tabpanel">
                                    <div class="form-group">
                                        <label>Описание клиента ({{ $lang->code }})</label>
                                        @include('admin.components.html_editor', ["name" => "$lang->code[content]", "required"])
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>

                    <hr>
                    <div class="form-group row">
                        <label class="col-md-6"></label>
                        <div class="col-md-6">
                            <button class="btn btn-success btn-block"><i class="fas fa-save"></i> Сохранить</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('layouts.admin')

@section('content')
    @php
        $langs = \App\Helpers\SysConfig::AllLanguage();
    @endphp

    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card card-cascade cascading-admin-card user-card">
            @include('admin.blocks.card_head', ["title" => "Клиенты", "title_child" => "Создать", "icon" => "fa-users"])
            <form method="post" action="{{ route('admin.clients.update', $data->id) }}" enctype="multipart/form-data">
                @method('put')
                @csrf
                <div class="card-body card-body-cascade">
                    <div class="form-group row">
                        <label class="col-md-4">Наименование</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" name="name" value="{{ $data->name }}" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-4">Логотип</label>
                        <div class="col-md-8">
                            <input type="file" name="logo" value="{{ $data->logo }}">
                        </div>
                    </div>

                    <div class="classic-tabs">
                        <div class="tabs-wrapper">
                            <ul class="nav tabs-blue" role="tablist">
                                @foreach($langs as $i=>$lang)
                                    <li class="nav-item">
                                        <a
                                            class="nav-link waves-light waves-effect waves-light {{ ($i == 0) ? 'active' : '' }}"
                                            data-toggle="tab"
                                            href="#tab_{{ $lang->id }}"
                                            role="tab"
                                            aria-selected="true">
                                            {{ $lang->name }} ({{ $lang->code }})
                                        </a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>

                        <div class="tab-content card">
                            @foreach($langs as $i=>$lang)
                                <div class="tab-pane fade {{ ($i == 0) ? 'active show' : '' }}" id="tab_{{ $lang->id }}" role="tabpanel">
                                    <div class="form-group">
                                        <label>Описание клиента ({{ $lang->code }})</label>
                                        @include('admin.components.html_editor', ["name" => "$lang->code[content]", "value"=>$data->translate($lang->code)->content])
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>

                    <hr>
                    <div class="form-group row">
                        <label class="col-md-6"></label>
                        <div class="col-md-6">
                            <button class="btn btn-success btn-block"><i class="fas fa-save"></i> Сохранить</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/clients/main.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <div class="card card-cascade cascading-admin-card user-card">
            @include('admin.blocks.card_head', ["title" => "Клиенты", "title_child" => "Список", "icon" => "fa-users"])

            <div class="card-body card-body-cascade">
                @include('admin.components.table',
                ["thead" => [ "Наименование", "Логотип"],
                 "data" => $data,
                 "cols" => ["name", "image"],
                 "cols_html" => ["", '<img src=":params" style="max-width: 100px">']
                ]
                )
            </div>
        </div>
    </div>
@endsection