routes/admin.php
<?php

use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\BrandsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ClientsController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\LocaleController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\BannerController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
    Route::get('home', [MainController::class, 'index'])->name('home');

    Route::resource('news', NewsController::class);
    Route::resource('language', LocaleController::class);
    Route::resource('clients', ClientsController::class);
    Route::resource('config', ConfigController::class);
    Route::resource('currency', CurrencyController::class);
    Route::get('convert_currency', [CurrencyController::class, 'ServiceConvertCurrency'])->name('convert_currency');
    Route::resource('categories', CategoryController::class);
    Route::resource('brands', BrandsController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('products', ProductController::class);
    Route::resource('order', OrderController::class);
    Route::resource('promotions', PromotionController::class);
    Route::resource('banners', BannerController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['LanguageMiddleware'])->group(function () {

    Route::get('/', [HomeController::class, 'index']);

    Route::get('/lang/{locale}', function ($locale) {
        if (!in_array($locale, ['en', 'ru'])) {
            abort(404);
        }
        session()->put('locale', $locale);
        return back();
    });

    Route::resource('products', ProductController::class);
    Route::get('products/filter/{filter}', [ProductController::class, 'filter']);
    Route::post('products/search', [ProductController::class, 'search']);

    Route::resource('about', AboutController::class);

    Route::resource('news', NewsController::class);

    Route::resource('promotions', PromotionController::class);

    Route::resource('orders', OrderController::class);

    /*Auth::routes([
        'login'    => false, // I ve mafe authorization via API - Evgeniy Tsoy
        'logout'   => true, // I will delete token on frontend - Evgeniy Tsoy
        'register' => true,
        'reset'    => true,   // for resetting passwords
        'confirm'  => false,  // for additional password confirmations
        'verify'   => false,  // for email verification
    ]);*/


// Authentication Routes...
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login']);
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

//Route::get('/admin/home', [\App\Http\Controllers\HomeController::class, 'index']);



    Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
        Lfm::routes();
    });


});

app/Models/Product.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer $id
 * @property boolean $state
 * @property string $sku
 * @property float $cost
 * @property integer $length_id
 * @property float $length
 * @property float $width
 * @property float $height
 * @property integer $weight_id
 * @property float $weight
 * @property int $minimal
 * @property integer $image_main
 * @property ProductAttribute[] $productAttributes
 * @property ProductBrand[] $productBrands
 * @property ProductCategory[] $productCategories
 * @property ProductFile[] $productFiles
 * @property ProductImage[] $productImages
 * @property ProductRecomend[] $productIdRecomends
 * @property ProductRecomend[] $productRecomends
 * @property ProductTranslation[] $productTranslations
 */
class Product extends Model implements TranslatableContract
{
    use Translatable;
    use HasFactory;
    use SoftDeletes;
    public $translatedAttributes = ['name', 'meta', 'description', 'requirement', 'version', 'buy_description', 'description_front', 'requirement_front', 'version_front', 'buy_description_front'];
    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['state', 'sku', 'cost', 'length_id', 'length', 'width', 'height', 'weight_id', 'weight', 'minimal', 'image_main'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productAttributes()
    {
        return $this->hasMany('App\Models\ProductAttribute');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productBrands()
    {
        return $this->hasMany('App\Models\ProductBrand');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productCategories()
    {
        return $this->hasMany('App\Models\ProductCategory');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productFiles()
    {
        return $this->hasMany('App\Models\ProductFile');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productImages()
    {
        return $this->hasMany('App\Models\ProductImage');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productIdRecomends()
    {
        return $this->hasMany('App\Models\ProductRecomend', 'product_id_recomend');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productRecomends()
    {
        return $this->hasMany('App\Models\ProductRecomend');
    }

    /**
     * Get description.
     *
     * @return string
     */
    public function getImageMainAttribute()
    {
        $imagemain = ProductImage::where("product_id","=",$this->attributes['id'])->where('on_main', '=', 1)->first();
        return $imagemain?$imagemain->image:"";
    }

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Faker\Core\File;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\Console\Input\Input;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $data = Product::translated()->paginate(env('PAGINATION_SIZE'));
        return view('admin.product.main', ["data" => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $imageSections = ['on_main', 'on_description', 'on_requirement', 'on_version', 'on_buy_description'];
        return view('admin.product.create', ['imageSections' => $imageSections]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $product = new Product();
        $langs = \App\Helpers\SysConfig::AllLanguage();
        $translations = [];
        foreach ($langs as $lang) {
            $translations[$lang->code] = [
                'name' => $request->get($lang->code)['name'],
                'meta' => $request->get($lang->code)['meta'],
                'description' => $request->get($lang->code)['description'],
                'requirement' => $request->get($lang->code)['requirement'],
                'version' => $request->get($lang->code)['version'],
                'buy_description' => $request->get($lang->code)['buy_description'],
            ];
        }
        $product->fill($translations);
        $product->sku = $request->get('sku');
        $product->cost = $request->get('cost');
        $product->length = $request->get('length');
        $product->width = $request->get('width');
        $product->height = $request->get('height');
        $product->length_id = $request->get('length_id');
        $product->weight = $request->get('weight');
        $product->weight_id = $request->get('weight_id');
        $product->save();
        $product->refresh();
        if (!empty($request->get('category'))) {
            $product->productCategories()->createMany($request->get('category'));
        }
        if (!empty($request->get('brands'))) {
            $product->productBrands()->createMany($request->get('brands'));
        }
        if (!empty($request->get('attribute'))) {
            $product->productAttributes()->createMany($request->get('attribute'));
        }
        $imageSections = ['on_main', 'on_description', 'on_requirement', 'on_version', 'on_buy_description'];
        foreach ($imageSections as $section) {
            if ($request->file($section)) {
                $extension = $request->file($section)->extension();
                $imageName = Str::random(40).'_'.$section;
                $path = 'products/'.$product->id;
                $image = ProductImage::create([
                    'product_id' => $product->id,
                    $section => 1,
                    "image" => 'data/'.$path.'/'.$imageName.'.'.$extension
                ]);
                $request->file($section)->storeAs($path, str_replace('data/'.$path.'/', '', $image->image), 'uploads');
            }
        }
        $message = $product ? 'Сохранение прошло успешно' : 'Не удалось сохранить';
        return Redirect::to(route('admin.products.index'))->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $data = Product::translated()->find($id);
        $langs = \App\Helpers\SysConfig::AllLanguage();
        $translations = [];
        foreach ($langs as $lang) {
            $translations[$lang->code] = [
                'name' => $data->translate($lang->code)->name,
                'meta' => $data->translate($lang->code)->meta,
                'description' => ltrim(strip_tags($data->translate($lang->code)->description)),
                'requirement' => ltrim(strip_tags($data->translate($lang->code)->requirement)),
                'version' => ltrim(strip_tags($data->translate($lang->code)->version)),
                'buy_description' => ltrim(strip_tags($data->translate($lang->code)->buy_description)),
            ];
        }
        $data->fill($translations);
        $imageSections = ['on_main', 'on_description', 'on_requirement', 'on_version', 'on_buy_description'];
        return view('admin.product.edit', ["data" => $data, 'imageSections' => $imageSections]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $langs = \App\Helpers\SysConfig::AllLanguage();
        $translations = [];
        foreach ($langs as $lang) {
            $translations[$lang->code] = [
                'name' => $request->get($lang->code)['name'],
                'meta' => $request->get($lang->code)['meta'],
                'description' => $request->get($lang->code)['description'],
                'requirement' => $request->get($lang->code)['requirement'],
                'version' => $request->get($lang->code)['version'],
                'buy_description' => $request->get($lang->code)['buy_description'],
            ];
        }
        //dd($translations);
        $product->fill($translations);
        $product->sku = $request->get('sku');
        $product->cost = $request->get('cost');
        $product->length = $request->get('length');
        $product->width = $request->get('width');
        $product->height = $request->get('height');
        $product->length_id = $request->get('length_id');
        $product->weight = $request->get('weight');
        $product->weight_id = $request->get('weight_id');
        $product->save();
        $product->productCategories()->delete();
        if (!empty($request->get('category'))) {
            $product->productCategories()->createMany($request->get('category'));
        }
        $product->productBrands()->delete();
        if (!empty($request->get('brands'))) {
            $product->productBrands()->createMany($request->get('brands'));
        }
        $product->productAttributes()->delete();
        if (!empty($request->get('attribute'))) {
            $product->productAttributes()->createMany($request->get('attribute'));
        }
        $imageSections = ['on_main', 'on_description', 'on_requirement', 'on_version', 'on_buy_description'];
        foreach ($imageSections as $section) {
            if ($request->file($section)) {
                $productImg = ProductImage::where(['product_id' => $id, $section => 1])->first();
                if ($productImg && file_exists($productImg->image)) {
                    unlink($productImg->image);
                }
                $extension = $request->file($section)->extension();
                $imageName = Str::random(40).'_'.$section;
                $path = 'products/'.$product->id;
                $image = ProductImage::updateOrCreate([
                    'product_id' => $id,
                    $section => 1
                ],[
                    'product_id' => $id,
                    $section => 1,
                    "image" => 'data/'.$path.'/'.$imageName.'.'.$extension
                ]);
                $request->file($section)->storeAs($path, str_replace('data/'.$path.'/', '', $image->image), 'uploads');
            }
        }
        return Redirect::to(route('admin.products.index'))->with('message', 'Редактирование прошло успешно');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $folder_path = public_path('data/products/'.$product->id);
        if (file_exists($folder_path)) {
            array_map('unlink', glob("$folder_path/*.*"));
            rmdir($folder_path);
        }
        $product->delete();
        return Redirect::to(route('admin.products.index'))->with('message', 'Удаление прошло успешно');
    }
}

resources/views/admin/product/create_tabs/attribut.blade.php
@foreach((new \App\Helpers\Referency())->all_attributes() as $attribute)

<div class="form-group row">
    <label class="col-md-3">{{ $attribute->name }}</label>
    <div class="col-md-9">
        <select class="form-control" name="attribute[][attribute_id]">
            @foreach($attribute->attributeParams as $param)
                <option value="{{ $param->id }}">{{ $param->name }}</option>
            @endforeach
        </select>
    </div>
</div>
@endforeach

resources/views/admin/product/create_tabs/dan.blade.php
<div class="form-group row">
    <label class="col-md-3">Артикуль / SKU</label>
    <div class="col-md-9">
        <input type="text" class="form-control needs-validation" name="sku" value="" required>
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3">Цена</label>
    <div class="col-md-9">
        <input type="number" class="form-control needs-validation" name="cost" value="" required>
    </div>
</div>


<div class="form-group row">
    <label class="col-md-3">Размеры</label>
    <div class="col-md-3">
        <input type="number" class="form-control needs-validation" name="length" value="" placeholder="Длина">
    </div>
    <div class="col-md-3">
        <input type="number" class="form-control needs-validation" name="width" value="" placeholder="Ширина">
    </div>
    <div class="col-md-3">
        <input type="number" class="form-control needs-validation" name="height" value="" placeholder="Высота">
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3">Единица измерения длины</label>
    <div class="col-md-9">
        <select class="form-control" name="length_id">
            @foreach((new \App\Helpers\Referency())->ref_length() as $ln)
            <option value="{{ $ln->id }}">{{ $ln->name }} ({{ $ln->abbreviate }})</option>
            @endforeach
        </select>
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3">Единица измерения веса</label>
    <div class="col-md-3">
        <input type="number" class="form-control needs-validation" name="weight" value="" placeholder="Вес">
    </div>
    <div class="col-md-6">
        <select class="form-control" name="weight_id">
            @foreach((new \App\Helpers\Referency())->ref_weight() as $rw)
                <option value="{{ $rw->id }}">{{ $rw->name }} ({{ $rw->abbreviate }})</option>
            @endforeach
        </select>
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3">Статус</label>
    <div class="col-md-9">
        <fieldset>
            <input class="form-check-input filled-in" name="status" value="1" type="checkbox" id="checkbox2">
            <label class="form-check-label" for="checkbox2">Активный</label>
        </fieldset>
    </div>
</div>

resources/views/admin/product/create_tabs/files.blade.php
@foreach($imageSections as $key => $value)
{{ $value }}
<div class="row">
{{--          <span class="input-group-btn">--}}
{{--            <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary btn-sm text-white">--}}
{{--              <i class="fas fa-picture-o"></i> Choose--}}
{{--            </a>--}}
{{--          </span>--}}
    <div class="col-6">
        <input id="thumbnail" class="form-control needs-validation" type="file" name="{{ $value }}">
    </div>
</div>
<br>
{{--<div id="holder2" class="row" style="margin-top:15px;max-height:100px;">--}}
{{--    <div class="col-md-3 row text-center">--}}
{{--        <div class="col-md-4">--}}
{{--            <i class="fas fa-3x fa-file-pdf text-danger"></i>--}}
{{--        </div>--}}
{{--        <div class="col-md-8">--}}
{{--            <input type="text" class="form-control" name="ru[file_text][1]" value="" placeholder="Название файла (ru)">--}}
{{--            <input type="text" class="form-control" name="en[file_text][1]" value="" placeholder="Название файла (en)">--}}
{{--            <input type="hidden" name="file[{{ $key }}][path]" value="">--}}
{{--            <input type="hidden" name="file[{{ $key }}][section]" value="{{ $value }}">--}}
{{--        </div>--}}
{{--    </div>--}}
{{--</div>--}}
@endforeach
@push('js')
{{--    <script>--}}
{{--        var lfm = function(id, type, options) {--}}
{{--            let button = document.getElementById(id);--}}

{{--            button.addEventListener('click', function () {--}}
{{--                var route_prefix = (options && options.prefix) ? options.prefix : '/filemanager';--}}
{{--                var target_input = document.getElementById(button.getAttribute('data-input'));--}}
{{--                let prev_id = button.getAttribute('data-preview');--}}
{{--                var target_preview = document.getElementById(prev_id);--}}

{{--                window.open(route_prefix + '?type=' + options.type || 'file', 'FileManager', 'width=900,height=600');--}}
{{--                window.SetUrl = function (items) {--}}
{{--                    var file_path = items.map(function (item) {--}}
{{--                        return item.url;--}}
{{--                    }).join(',');--}}

{{--                    // set the value of the desired input to image url--}}
{{--                    target_input.value = file_path;--}}
{{--                    target_input.dispatchEvent(new Event('change'));--}}

{{--                    // clear previous preview--}}
{{--                    //target_preview.innerHtml = '';--}}

{{--                    // set or change the preview image src--}}

{{--                    items.forEach(function (item) {--}}
{{--                        let html = '<div class="col-md-3 row text-center">\n' +--}}
{{--                            '        <div class="col-md-4">\n' +--}}
{{--                            '            <i class="fas fa-3x fa-file-'+item.icon+' text-danger"></i>\n' +--}}
{{--                            '        </div>\n' +--}}
{{--                            '        <div class="col-md-8">\n' +--}}
{{--                            '            <input type="text" class="form-control" name="ru[file_text][1]" value="'+item.name+'" placeholder="Название файла (ru)">\n' +--}}
{{--                            '            <input type="text" class="form-control" name="en[file_text][1]" value="'+item.name+'" placeholder="Название файла (en)">\n' +--}}
{{--                            '            <input type="hidden" name="file[1][path]" value="'+item.url+'">\n' +--}}
{{--                            '        </div>\n' +--}}
{{--                            '    </div>';--}}

{{--                        $('#'+prev_id).append(html);--}}

{{--                        //target_preview.append(html);--}}
{{--                        //console.log(item);--}}
{{--                        /*--}}
{{--                        let img = document.createElement('img')--}}
{{--                        img.setAttribute('style', 'height: 5rem')--}}
{{--                        img.setAttribute('src', item.thumb_url)--}}
{{--                        target_preview.appendChild(img);--}}
{{--                        */--}}
{{--                    });--}}

{{--                    // trigger change event--}}
{{--                    target_preview.dispatchEvent(new Event('change'));--}}
{{--                };--}}
{{--            });--}}
{{--        };--}}

{{--        lfm('lfm', 'file', {prefix: route_prefix});--}}
{{--    </script>--}}
@endpush

resources/views/admin/product/create_tabs/link.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <div>
                    <a class="float-right" href="{{ route('admin.brands.index') }}" target="_blank"><i class="fas fa-link"></i></a>
                    <a class="float-right mr-3" id="reload_brand" href="#"><i class="fas fa-sync"></i></a>
                    <h5>Бренды</h5>
                </div>
                <div id="list_brands">
                @foreach((new\App\Helpers\Referency)->all_brands() as $brand)
                    <fieldset>
                        <input class="form-check-input filled-in" name="brands[][brand_id]" value="{{ $brand->id }}" type="checkbox" id="ch_brand_{{ $brand->id }}">
                        <label class="form-check-label" for="ch_brand_{{ $brand->id }}">{{ $brand->name }}</label>
                    </fieldset>
                @endforeach
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <div>
                    <a class="float-right" href="{{ route('admin.categories.index') }}" target="_blank"><i class="fas fa-link"></i></a>
                    <a class="float-right mr-3" id="reload_category" href="#"><i class="fas fa-sync"></i></a>
                    <h5>Категории</h5>
                </div>
                <div id="list_categories">
                    @foreach((new\App\Helpers\Referency)->all_category() as $category)
                        <fieldset>
                            <input class="form-check-input filled-in" name="category[][category_id]" value="{{ $category->id }}" type="checkbox" id="ch_category_{{ $category->id }}">
                            <label class="form-check-label" for="ch_category_{{ $category->id }}">{{ $category->name }}</label>
                        </fieldset>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>

@push('js')
    <script>
        $('#reload_brand').click(function(e){
            e.preventDefault()

            $.get('/api/brands', function(data){
                $('#list_brands').html('');
                $.each(data, function(i, e){
                    let html = '<fieldset>\n' +
                        '<input class="form-check-input filled-in" name="brands[]" value="'+e.id+'" type="checkbox" id="ch_brand_'+e.id+'">\n' +
                        '<label class="form-check-label" for="ch_brand_'+e.id+'">'+e.name+'</label>\n' +
                        '</fieldset>';
                    $('#list_brands').append(html);
                })
            })
        })

        $('#reload_category').click(function(e){
            e.preventDefault()

            $.get('/api/categories', function(data){
                $('#list_categories').html('');
                $.each(data, function(i, e){
                    let html = '<fieldset>\n' +
                        '<input class="form-check-input filled-in" name="brands[]" value="'+e.id+'" type="checkbox" id="ch_category_'+e.id+'">\n' +
                        '<label class="form-check-label" for="ch_category_'+e.id+'">'+e.name+'</label>\n' +
                        '</fieldset>';
                    $('#list_categories').append(html);
                })
            })
        })
    </script>
@endpush

resources/views/admin/product/create_tabs/main.blade.php
@php
    $langs = \App\Helpers\SysConfig::AllLanguage();
@endphp

<div class="classic-tabs">
    <div class="tabs-wrapper">
        <ul class="nav tabs-dark" role="tablist">
            @foreach($langs as $i=>$lang)
                <li class="nav-item">
                    <a
                        class="nav-link waves-light waves-effect waves-light {{ ($i == 0) ? 'active' : '' }}"
                        data-toggle="tab"
                        href="#tab_{{ $lang->id }}"
                        role="tab"
                        aria-selected="true">
                        {{ $lang->name }} ({{ $lang->code }})
                    </a>
                </li>
            @endforeach
        </ul>
    </div>
    <div class="tab-content card">
        @foreach($langs as $i=>$lang)
            <div class="tab-pane fade {{ ($i == 0) ? 'active show' : '' }}" id="tab_{{ $lang->id }}" role="tabpanel">
                <div class="form-group">
                    <label>Наименование ({{ $lang->code }})</label>
                    <input type="text" class="form-control needs-validation" name="{{ $lang->code }}[name]" value="" required>
                </div>
                <div class="form-group">
                    <label>Meta ({{ $lang->code }})</label>
                    <textarea rows="6" style="resize: none" class="form-control needs-validation" name="{{ $lang->code }}[meta]" required></textarea>
                </div>
                <div class="form-group">
                    <label>Описание ({{ $lang->code }})</label>
                    @include('admin.components.html_editor', ["name" => "$lang->code[description]", "required"])
                </div>
                <div class="form-group">
                    <label>Мин. требования ({{ $lang->code }})</label>
                    @include('admin.components.html_editor', ["name" => "$lang->code[requirement]", "required"])
                </div>
                <div class="form-group">
                    <label>Версии ({{ $lang->code }})</label>
                    @include('admin.components.html_editor', ["name" => "$lang->code[version]", "required"])
                </div>
                <div class="form-group">
                    <label>Купить ({{ $lang->code }})</label>
                    @include('admin.components.html_editor', ["name" => "$lang->code[buy_description]", "required"])
                </div>
            </div>
        @endforeach
    </div>
</div>