routes/admin.php
<?php

use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\BrandsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ClientsController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\LocaleController;
use App\Http\Controllers\Admin\MainController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\BannerController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
    Route::get('home', [MainController::class, 'index'])->name('home');

    Route::resource('news', NewsController::class);
    Route::resource('language', LocaleController::class);
    Route::resource('clients', ClientsController::class);
    Route::resource('config', ConfigController::class);
    Route::resource('currency', CurrencyController::class);
    Route::get('convert_currency', [CurrencyController::class, 'ServiceConvertCurrency'])->name('convert_currency');
    Route::resource('categories', CategoryController::class);
    Route::resource('brands', BrandsController::class);
    Route::resource('attributes', AttributeController::class);
    Route::resource('products', ProductController::class);
    Route::resource('order', OrderController::class);
    Route::resource('promotions', PromotionController::class);
    Route::resource('banners', BannerController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['LanguageMiddleware'])->group(function () {

    Route::get('/', [HomeController::class, 'index']);

    Route::get('/lang/{locale}', function ($locale) {
        if (!in_array($locale, ['en', 'ru'])) {
            abort(404);
        }
        session()->put('locale', $locale);
        return back();
    });

    Route::resource('products', ProductController::class);
    Route::get('products/filter/{filter}', [ProductController::class, 'filter']);
    Route::post('products/search', [ProductController::class, 'search']);

    Route::resource('about', AboutController::class);

    Route::resource('news', NewsController::class);

    Route::resource('promotions', PromotionController::class);

    Route::resource('orders', OrderController::class);

    /*Auth::routes([
        'login'    => false, // I ve mafe authorization via API - Evgeniy Tsoy
        'logout'   => true, // I will delete token on frontend - Evgeniy Tsoy
        'register' => true,
        'reset'    => true,   // for resetting passwords
        'confirm'  => false,  // for additional password confirmations
        'verify'   => false,  // for email verification
    ]);*/


// Authentication Routes...
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login']);
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

// Registration Routes...
    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register']);

// Password Reset Routes...
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

//Route::get('/admin/home', [\App\Http\Controllers\HomeController::class, 'index']);



    Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
        Lfm::routes();
    });


});

app/Models/Currency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $symbol
 * @property float $rate
 * @property boolean $on_default
 * @property boolean $position_left
 */
class Currency extends Model
{
    /**
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'currency';

    /**
     * The "type" of the auto-incrementing ID.
     * 
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['code', 'name', 'symbol', 'rate', 'on_default', 'position_left'];

}

app/Http/Controllers/Admin/CurrencyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\ConvertCurrency;
use App\Http\Controllers\Controller;
use App\Models\Currency;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class CurrencyController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $data = Currency::query()->get([
            "id",
            "code",
            "name",
            "symbol",
            "rate",
            DB::raw("case when on_default then 'Да' else 'Нет' end as on_default"),
            DB::raw("case when position_left then 'Слева' else 'Справа' end as position_left")
        ]);
        return view('admin.currency.main', ["data" => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $cc = new ConvertCurrency();
        $data = $cc->getAllCurrency();
        $data_currency = $cc->beautifullyCode($data);
        $data_currency_json = json_encode($data_currency);
        return view('admin.currency.create',
            ['data_currency' => $data_currency, 'data_currency_json' => $data_currency_json]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $code = $request->input('code');
        $name = $request->input('name');
        $symbol = $request->input('symbol');
        $rate = $request->input('rate');
        $position = (bool) $request->input('position_left');
        $default = ($request->has('on_default'));

        $cr = new Currency();
        $cr->code = $code;
        $cr->name = $name;
        $cr->symbol = $symbol;
        $cr->rate = $rate;
        $cr->position_left = $position;
        $cr->on_default = $default;
        $cr->save();

        if($default){
            $id = $cr->id;
            Currency::query()->whereKeyNot($id)->update([
                "on_default" => false
            ]);
        }

        return Redirect::to(route('admin.currency.index'))->with('message', 'Сохранение прошло успешно');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $data = Currency::find($id);

        $cc = new ConvertCurrency();
        $data_currency = $cc->beautifullyCode($cc->getAllCurrency());
        $data_currency_json = json_encode($data_currency);

        return view('admin.currency.edit', [
            "data" => $data,
            'data_currency' => $data_currency,
            'data_currency_json' => $data_currency_json
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(Request $request, int $id)
    {
        $code = $request->input('code');
        $name = $request->input('name');
        $symbol = $request->input('symbol');
        $rate = $request->input('rate');
        $position = (bool) $request->input('position_left');
        $default = ($request->has('on_default'));

        $cr = Currency::find($id);
        $cr->code = $code;
        $cr->name = $name;
        $cr->symbol = $symbol;
        $cr->rate = $rate;
        $cr->position_left = $position;
        $cr->on_default = $default;
        $cr->save();

        if($default){
            Currency::query()->whereKeyNot($id)->update([
                "on_default" => false
            ]);
        }

        return Redirect::to(route('admin.currency.index'))->with('message', 'Сохранение прошло успешно');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $ls = Currency::all();
        if(count($ls) <= 1){
            return Redirect::to(route('admin.language.index'))
                ->withErrors(["errorMessage" => "Удаление единственного валюты запрещено!"]);
        }

        $c = Currency::find($id);
        if($c->on_default){
            return Redirect::to(route('admin.currency.index'))
                ->withErrors(["errorMessage" => "Удаление основной валюты запрещено!"]);
        }
        $c->delete();
        return Redirect::to(route('admin.currency.index'))->with('message', 'Удаление прошло успешно');
    }


    public function ServiceConvertCurrency()
    {
        $cr = new ConvertCurrency();
        $text = $cr->start();
        return Redirect::to(route('admin.currency.index'))->with('message', $text);
    }
}

resources/views/admin/currency/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card card-cascade cascading-admin-card user-card">
            @include('admin.blocks.card_head', ["title" => "Валюта", "title_child" => "Создать", "icon" => "fa-dollar-sign"])
            <form method="post" action="{{ route('admin.currency.store') }}">
                @csrf
                <div class="card-body card-body-cascade">
                    <div class="form-group row">
                        <label class="col-md-3">Код</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="code" value="" list="code_currency">
                            <datalist id="code_currency">
                                @foreach($data_currency as $dc)
                                    <option value="{{ $dc['code'] }}">{{ $dc['name'] }}</option>
                                @endforeach
                            </datalist>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Наименование</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="name" value="">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Символ</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="symbol" value="">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Курс</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="rate" value="">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Позиция</label>
                        <div class="col-md-9">
                            <select class="form-control" name="position_left" style="display: block">
                                <option value="true">Слева</option>
                                <option value="false">Справа</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3"></label>
                        <div class="col-md-9">
                            <fieldset class="form-check mt-4">
                                <input class="form-check-input filled-in" name="on_default" type="checkbox" id="checkbox2">
                                <label class="form-check-label" for="checkbox2">Выбрать как основной</label>
                            </fieldset>
                        </div>
                    </div>


                    <hr>
                    <div class="form-group row">
                        <label class="col-md-3"></label>
                        <div class="col-md-9">
                            <button class="btn btn-success btn-block"><i class="fas fa-save"></i> Сохранить</button>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3"></label>
                        <div class="col-md-9">
                            <label class="text-info">
                                Курс валют взят с сайта {{ env('CURRENCY_SERVICE') }}
                            </label>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
@endsection

@push('js')
    <script>
        let cr = JSON.parse('{!! $data_currency_json !!}');
        console.log(cr);
        $("input[name=code]").on('input', function () {
            var val = this.value;
            $.each(cr, function(i, e){
                if(e.code === val){
                    $('input[name=name]').val(e.name);
                    $('input[name=rate]').val(e.rate);
                }
            })
        });
    </script>
@endpush

resources/views/admin/currency/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card card-cascade cascading-admin-card user-card">
            @include('admin.blocks.card_head', ["title" => "Валюта", "title_child" => "Создать", "icon" => "fa-dollar-sign"])
            <form method="post" action="{{ route('admin.currency.update', $data->id) }}">
                @method('put')
                @csrf
                <div class="card-body card-body-cascade">
                    <div class="form-group row">
                        <label class="col-md-3">Код</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="code" value="{{ $data->code }}" list="code_currency">
                            <datalist id="code_currency">
                                @foreach($data_currency as $dc)
                                    <option value="{{ $dc['code'] }}">{{ $dc['name'] }}</option>
                                @endforeach
                            </datalist>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Наименование</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="name" value="{{ $data->name }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Символ</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="symbol" value="{{ $data->symbol }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Курс</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="rate" value="{{ $data->rate }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3">Позиция</label>
                        <div class="col-md-9">
                            <select class="form-control" name="position_left" style="display: block">
                                <option value="true" {{ ($data->position_left) ? 'selected' : '' }}>Слева</option>
                                <option value="false" {{ ($data->position_left) ? '' : 'selected' }}>Справа</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3"></label>
                        <div class="col-md-9">
                            <fieldset class="form-check mt-4">
                                <input class="form-check-input filled-in"
                                       name="on_default"
                                       type="checkbox"
                                       id="checkbox2"
                                    {{ ($data->on_default) ? 'checked' : '' }}
                                >
                                <label class="form-check-label" for="checkbox2">Выбрать как основной</label>
                            </fieldset>
                        </div>
                    </div>


                    <hr>
                    <div class="form-group row">
                        <label class="col-md-3"></label>
                        <div class="col-md-9">
                            <button class="btn btn-success btn-block"><i class="fas fa-save"></i> Сохранить</button>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3"></label>
                        <div class="col-md-9">
                            <label class="text-info">
                                Курс валют взят с сайта {{ env('CURRENCY_SERVICE') }}
                            </label>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
@endsection

@push('js')
    <script>
        let cr = JSON.parse('{!! $data_currency_json !!}');
        console.log(cr);
        $("input[name=code]").on('input', function () {
            var val = this.value;
            $.each(cr, function(i, e){
                if(e.code === val){
                    $('input[name=name]').val(e.name);
                    $('input[name=rate]').val(e.rate);
                }
            })
        });
    </script>
@endpush

resources/views/admin/currency/main.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <div class="card card-cascade cascading-admin-card user-card">
            @include('admin.blocks.card_head', ["title" => "Локализация", "title_child" => "Валюта", "icon" => "fa-dollar-sign"])

            <div class="card-body card-body-cascade">
                @include('admin.components.table',
                ["thead" => [ "Наименование", "Код", "Символ", "Курс", "Позиция", "Основной"],
                 "data" => $data,
                 "cols" => ["name", "code", "symbol", "rate", "position_left", "on_default"],
                 "cols_html" => ["", "", '', '', '', '']
                ]
                )
            </div>

            <div class="card-footer text-right">
                <a href="{{ route('admin.convert_currency') }}" class="btn btn-info btn-sm">Обновить курс валют</a>
            </div>
        </div>
    </div>
@endsection